services:
  postgres:
    build:
      dockerfile: postgres.Dockerfile
    ports:
      - 5432:5432

  pgadmin:
    build:
      dockerfile: pgadmin.Dockerfile
    ports:
      - 8080:8080

  backend:
    build:
      dockerfile: backend.Dockerfile
    ports:
      - 5000:5000

  frontend:
    build:
      dockerfile: frontend.Dockerfile
    ports:
      - 80:3000
