services:
  postgres:
    build:
      dockerfile: postgres.Dockerfile
      context: .
    ports:
      - 5432:5432

  pgadmin:
    build:
      dockerfile: pgadmin.Dockerfile
      context: .
    ports:
      - 8080:8080
    depends_on:
      - postgres

  backend:
    build:
      dockerfile: backend.Dockerfile
      context: .
    ports:
      - 5000:5000
    depends_on:
      - postgres

  frontend:
    build:
      dockerfile: frontend.Dockerfile
      context: .
    ports:
      - 80:3000
    depends_on:
      - backend
